site_name: Pagatu MOV - Desarrollo de Aplicaciones Móviles
site_url: https://262mov.github.io/pagatu-mov/
docs_dir: docs

nav:
  - Inicio: index.md
  - Guía de Proyecto Sello:
      - Guía del proyecto: proyecto-sello/index.md
  - Silabos:
      - Silabo 2026-1: silabo_mov_2026_1.md
      - Silabo 2026-2: silabo_mov_2026_2.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

plugins:
  - search
